/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package train.ticket;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
/**
 *
 * @author HP
 */
public class Trainticketsystem extends javax.swing.JFrame {

    /**
     * Creates new form Trainticketsystem
     */
    public Trainticketsystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRStand = new javax.swing.JRadioButton();
        jREco = new javax.swing.JRadioButton();
        jRFirstclass = new javax.swing.JRadioButton();
        jRreturn = new javax.swing.JRadioButton();
        jRadultyes = new javax.swing.JRadioButton();
        jRchildyes = new javax.swing.JRadioButton();
        jRsingle = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxdestination = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabelSubTotal = new javax.swing.JLabel();
        jLabelTax = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLblSubTotal1 = new javax.swing.JLabel();
        jLblTax1 = new javax.swing.JLabel();
        jLblTotal1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jClass = new javax.swing.JLabel();
        jTicketType = new javax.swing.JLabel();
        jA = new javax.swing.JLabel();
        jC = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jFrom = new javax.swing.JLabel();
        jTo = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jTime = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTicketNo = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPrice = new javax.swing.JLabel();
        jRoute = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1400, 700));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 8, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 96)); // NOI18N
        jLabel1.setText("   Trainticket system");

        jLabel2.setFont(new java.awt.Font("Webdings", 0, 96)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/train/ticket/train ticket symbol.jpeg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/train/ticket/train ticket symbol 2.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1186, 1186, 1186)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))))
                .addGap(127, 127, 127))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Class");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Ticket type");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Adult");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Child");

        jRStand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRStand.setText("Standard");
        jRStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRStandActionPerformed(evt);
            }
        });

        jREco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jREco.setText("Economy");

        jRFirstclass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRFirstclass.setText("First class");

        jRreturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRreturn.setText("Return");
        jRreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRreturnActionPerformed(evt);
            }
        });

        jRadultyes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadultyes.setText("yes");
        jRadultyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadultyesActionPerformed(evt);
            }
        });

        jRchildyes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRchildyes.setText("yes");
        jRchildyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRchildyesActionPerformed(evt);
            }
        });

        jRsingle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRsingle.setText("Single");
        jRsingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRsingleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Destination");

        jComboBoxdestination.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxdestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chennai", "Hyderabad", "Vishakapatnam" }));
        jComboBoxdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxdestinationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRStand, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel7)
                                .addGap(142, 142, 142)
                                .addComponent(jLabel8)
                                .addGap(185, 185, 185)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jREco)
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRreturn)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(259, 259, 259)
                                                .addComponent(jLabel10))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(250, 250, 250)
                                                .addComponent(jComboBoxdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRsingle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadultyes)
                                        .addGap(187, 187, 187)
                                        .addComponent(jRchildyes)
                                        .addGap(20, 20, 20))))
                            .addComponent(jRFirstclass, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadultyes)
                    .addComponent(jRsingle)
                    .addComponent(jRStand)
                    .addComponent(jRchildyes))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jRreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jREco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(jRFirstclass)
                        .addGap(60, 60, 60))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabelSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSubTotal.setText("Sub Total");

        jLabelTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTax.setText("Tax");

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTotal.setText("Total");

        jLblSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblSubTotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLblTax1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblTax1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLblTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblTotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Total");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/train/ticket/Reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/train/ticket/close Jframe.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelTax)
                    .addComponent(jLabelSubTotal))
                .addGap(99, 99, 99)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLblTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(jLblSubTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblTax1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubTotal)
                    .addComponent(jLblSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTax1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelTax)
                        .addGap(13, 13, 13)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Class");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Ticket Type");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Adult");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Child");

        jClass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jTicketType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTicketType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("From");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("To");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Date");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setText("Time");

        jFrom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jTo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setText("Ticket No.");

        jTicketNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTicketNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel33.setText("Price");

        jPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jRoute.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRoute.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setText("Route");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jClass, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel31)
                                    .addComponent(jTicketNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel36)
                                    .addComponent(jPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(jRoute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTicketNo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel19))
                .addGap(93, 93, 93)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)))
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(11, 11, 11))))
                    .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2634, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRreturnActionPerformed

    private void jRStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRStandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRStandActionPerformed

    private void jRsingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRsingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRsingleActionPerformed

    private void jRadultyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadultyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadultyesActionPerformed

    private void jRchildyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRchildyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRchildyesActionPerformed

    private void jComboBoxdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxdestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxdestinationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ====================== TIME===============================
       
        // ====================== TIME===============================
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        jTime.setText(tTime.format(timer.getTime()));
        //======================== DATE===============================
        SimpleDateFormat tdate = new SimpleDateFormat("dd:MM:yyyy");
        jDate.setText(tdate.format(timer.getTime()));
 
        
       jFrom.setText("Vijayawada *");
       jTo.setText((String) jComboBoxdestination.getSelectedItem()+ " *");
       //==========================RANDOM NUMBER GENERATOR==============
       
       int num1;
       String q1="";
       num1=1325+ (int) (Math.random()*4238);
       q1+=num1+1325;
       jTicketNo.setText(q1);
       //=================================================================
       jRoute.setText("ANY");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            jLblSubTotal1.setText(null);
            jLblTax1.setText(null);
            jLblTotal1.setText(null);
            jTicketNo.setText(null);
            jRoute.setText(null);
            jLblTotal1.setText(null);
            jPrice.setText(null);
            jClass.setText(null);
            jTicketType.setText(null);
            jA.setText(null);
            jC.setText(null);
            
            
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                 // TODO add your handling code here:
                 System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
         
       
        
        double tax =20.00;
        double MilesK8=55.78;
        double MilesK20=50.00;
        double MilesK30=60.00;
        double totalCost, eco=40.00, fcla=65.50;
        
        if((jRStand.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *MilesK8)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK8 + totalCost));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRStand.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *(MilesK8*2))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK8 + totalCost) *2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRStand.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *MilesK8)/100;
                String sTax=String.format("Rs%.2f", totalCost- 18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK8 + totalCost)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRStand.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *(MilesK8*2))/100;
                String sTax=String.format("Rs%.2f", totalCost - 18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f",((MilesK8 + totalCost)*2)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRStand.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *MilesK20)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK20 + totalCost));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRStand.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *(MilesK20*2))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK20 + totalCost)*2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRStand.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *MilesK20)/100;
                String sTax=String.format("Rs%.2f", totalCost-18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK20 + totalCost)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRStand.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *(MilesK20*2))/100;
                String sTax=String.format("Rs%.2f", totalCost-18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", ((MilesK20 + totalCost)*2)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRStand.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *MilesK30)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK30 + totalCost));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRStand.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *(MilesK30*2))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK30 + totalCost)*2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRStand.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *MilesK30)/100;
                String sTax=String.format("Rs%.2f", totalCost -18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK30 + totalCost)- 18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
         else if((jRStand.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *(MilesK30*2))/100;
                String sTax=String.format("Rs%.2f", totalCost -18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK30 + totalCost)*2- 18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("STD");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jREco.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *(MilesK8+eco))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2+eco);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK8 + totalCost+eco));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jREco.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *(MilesK8*2+eco))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2+eco);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK8 + totalCost+eco) *2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jREco.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *MilesK8+eco)/100;
                String sTax=String.format("Rs%.2f", eco+totalCost- 18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2+eco);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK8 +eco+ totalCost)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jREco.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *(MilesK8*2+eco))/100;
                String sTax=String.format("Rs%.2f", eco+totalCost - 18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK8*2+eco);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f",((MilesK8 +eco+ totalCost)*2)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jREco.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *MilesK20+eco)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK20*2+eco);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK20 + totalCost+eco));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jREco.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *(MilesK20*2+eco))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK20*2+eco);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK20 + totalCost+eco)*2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jREco.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *MilesK20+eco)/100;
                String sTax=String.format("Rs%.2f", totalCost-18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",eco+MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (MilesK20 +eco+ totalCost)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jREco.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *(MilesK20*2+eco))/100;
                String sTax=String.format("Rs%.2f", totalCost-18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",eco+MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", ((eco+MilesK20 + totalCost)*2)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jREco.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *MilesK30+eco)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",eco+MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (eco+MilesK30 + totalCost));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jREco.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *(MilesK30*2+eco))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",eco+MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (eco+MilesK30 + totalCost)*2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jREco.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *MilesK30+eco)/100;
                String sTax=String.format("Rs%.2f", totalCost -18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",eco+MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (eco+MilesK30 + totalCost)- 18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
         else if((jREco.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *(MilesK30*2+eco))/100;
                String sTax=String.format("Rs%.2f", totalCost -18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",MilesK30*2+eco);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (eco+MilesK30 + totalCost)*2- 18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("ECO");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
         else if((jRFirstclass.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *MilesK8+fcla)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK8 + totalCost));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *(MilesK8*2+fcla))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK8 + totalCost) *2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRATCLASS");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *MilesK8+fcla)/100;
                String sTax=String.format("Rs%.2f", totalCost- 18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK8 + totalCost)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Chennai"))
        {
                totalCost=(tax *(MilesK8*2+fcla))/100;
                String sTax=String.format("Rs%.2f", totalCost - 18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK8*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f",((fcla+MilesK8 + totalCost)*2)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *MilesK20+fcla)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK20 + totalCost));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *(MilesK20*2+fcla))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK20 + totalCost)*2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *MilesK20+fcla)/100;
                String sTax=String.format("Rs%.2f", totalCost-18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK20 + totalCost)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Hyderabad"))
        {
                totalCost=(tax *(MilesK20*2+fcla))/100;
                String sTax=String.format("Rs%.2f", totalCost-18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK20*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", ((fcla+MilesK20 + totalCost)*2)-18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRsingle.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *MilesK30+fcla)/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK30 + totalCost));
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText(" ONE WAY");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRreturn.isSelected()) && (jRadultyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *(MilesK30*2+fcla))/100;
                String sTax=String.format("Rs%.2f", totalCost);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK30 + totalCost)*2);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText("RETURN");
                jA.setText("ONE");
                jC.setText("NIL");    
                
        }
        else if((jRFirstclass.isSelected()) && (jRsingle.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *MilesK30+fcla)/100;
                String sTax=String.format("Rs%.2f", totalCost -18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK30 + totalCost)- 18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText(" ONE WAY");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
         else if((jRFirstclass.isSelected()) && (jRreturn.isSelected()) && (jRchildyes.isSelected())  && jComboBoxdestination.getSelectedItem().equals("Vishakapatnam"))
        {
                totalCost=(tax *(MilesK30*2+fcla))/100;
                String sTax=String.format("Rs%.2f", totalCost -18);
                jLblTax1.setText(sTax);
                String subtotal=String.format("Rs%.2f",fcla+MilesK30*2);
                jLblSubTotal1.setText(subtotal);
                String Total = String.format("Rs%.2f", (fcla+MilesK30 + totalCost)*2- 18);
                jLblTotal1.setText(Total);
                jPrice.setText(Total);
                jClass.setText("FIRSTCLASS");
                jTicketType.setText("RETURN");
                jA.setText("NIL");
                jC.setText("ONE");    
                
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trainticketsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trainticketsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trainticketsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trainticketsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trainticketsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jC;
    private javax.swing.JLabel jClass;
    private javax.swing.JComboBox<String> jComboBoxdestination;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jFrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSubTotal;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLblSubTotal1;
    private javax.swing.JLabel jLblTax1;
    private javax.swing.JLabel jLblTotal1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPrice;
    private javax.swing.JRadioButton jREco;
    private javax.swing.JRadioButton jRFirstclass;
    private javax.swing.JRadioButton jRStand;
    private javax.swing.JRadioButton jRadultyes;
    private javax.swing.JRadioButton jRchildyes;
    private javax.swing.JLabel jRoute;
    private javax.swing.JRadioButton jRreturn;
    private javax.swing.JRadioButton jRsingle;
    private javax.swing.JLabel jTicketNo;
    private javax.swing.JLabel jTicketType;
    private javax.swing.JLabel jTime;
    private javax.swing.JLabel jTo;
    // End of variables declaration//GEN-END:variables
}
